### ISSUE TITLE
"attached" not called on nested custom elements

### ISSUE THREAD

**Issue by atornes** [aurelia/framework#35]
When nesting a custom element inside another custom element. The attached function is not called for the nested element.

**Comment by EisenbergEffect** [comment]
Can you provide some more information on this? Are you using shadow DOM? Can you show some code?

**Comment by atornes** [comment]
Sorry, details are important. Here is a more detailed test case.

Shadow DOM was not used.

Starting from the aurelia/skeleton-navigation.

Add src/nested.html:
```html
<template>
  This is nested
</template>
```

Add src/nested.js:
```js
import {Behavior} from 'aurelia-framework';

export class Nested {
  static metadata(){ return Behavior.customElement('nested'); }

  attached(){
    console.log('Nested attached');
  }
}
```

Modify src/nav-bar.js, (add function to log attached)
```js
attached(){
    console.log('NavBar attached');
}
```

Import and add "nested" in nav-bar.html:
```html
<template>
  <import from='./nested'></import>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <nested></nested>
    <div class="navbar-header">
    ........
```

Run in browser and check log, "NavBar attached" is written out but not "Nested attached".


Really love the framework so far. Clean and very simple to get started :+1:

**Comment by EisenbergEffect** [comment]
Can you confirm that you added a `<content></content>` element inside your nav bar's view? That's how it knows where to place the nested content. Without that, it won't work. Please let me know.

**Comment by atornes** [comment]
The nesting is not done in app.html. So this is not related to the content element. 

The desired markup is added to the DOM and the bind() function is invoked. It's just that the attached() function is not invoked. 

Please follow the simple steps above to reproduce.

**Comment by EisenbergEffect** [comment]
I'm sorry. I misread the code. Let me re-open this and see if I can tell what is going on. Thanks for your patience!

**Comment by andrewmunsell** [comment]
Looks like I am running into the same issue-- is there an update on this?

**Comment by EisenbergEffect** [comment]
Sorry. We haven't taken a look at this particular issue yet. I'm definitely surprised that this is happening. I'll bump the priority on this up and try to look at it in the next few days. Hopefully we can get a fix into the next release.

**Comment by EisenbergEffect** [comment]
Fixed in 31702e14f9da0bd844ef60d0dd375c7a375f3d7f  Going out in the next release this week.

**Comment by yd021976** [comment]
Hello, got the latest aurelia framework version and it seems that nested custome element « attached » is still not called.

Note that my nested custom element contains a repeat.for directive. Like this :
<parent-element>
   <nested-element repeat.for=« layers »></nested-element>
</parent-element>

In this case, « nested-element » attached method is never call. Only « bind » method is called.
